name: Build TowerDefense

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake (Win32)
      run: cmake -B build -A Win32 -DCMAKE_BUILD_TYPE=Release

    - name: Build Release
      run: cmake --build build --config Release

    - name: Configure CMake (Debug)
      run: cmake -B build-debug -A Win32 -DCMAKE_BUILD_TYPE=Debug

    - name: Build Debug
      run: cmake --build build-debug --config Debug

    - name: Prepare package
      run: |
        mkdir package
        xcopy build\Release\* package\ /E /I /Y

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TowerDefense-Windows
        path: package
